Generate map data to be used on https://www.datawrapper.de/

all_colocs.csv from https://www.feitsui.com/en/article/26
worldcities.csv from https://simplemaps.com/data/world-cities

In [1]:
import polars as pl
import seaborn as sns
import matplotlib.pyplot as plt
print("Imported libs")

Imported libs

In [2]:
colocs = pl.read_csv("all_colocs.csv")
colocs

shape: (307, 3)
┌──────────────────┬─────────────┬─────────┐
│ colocationCenter ┆ city        ┆ country │
│ ---              ┆ ---         ┆ ---     │
│ str              ┆ str         ┆ str     │
╞══════════════════╪═════════════╪═════════╡
│ TIA              ┆ Tirana      ┆ Albania │
│ ALG              ┆ Algiers     ┆ Algeria │
│ AAE              ┆ Annaba      ┆ Algeria │
│ ORN              ┆ Oran        ┆ Algeria │
│ LAD              ┆ Luanda      ┆ Angola  │
│ …                ┆ …           ┆ …       │
│ VIX              ┆ Vitoria     ┆ Brazil  │
│ BBI              ┆ Bhubaneswar ┆ India   │
│ KJA              ┆ Krasnoyarsk ┆ Russia  │
│ MLA              ┆ Valletta    ┆ Malta   │
│ BEY              ┆ Beirut      ┆ Lebanon │
└──────────────────┴─────────────┴─────────┘

In [3]:
world_cities = pl.read_csv("worldcities.csv", ignore_errors=True)
world_cities

shape: (48_059, 11)
┌────────────┬────────────┬──────────┬──────────┬───┬────────────┬─────────┬───────────┬───────────┐
│ city       ┆ city_ascii ┆ lat      ┆ lng      ┆ … ┆ admin_name ┆ capital ┆ populatio ┆ id        │
│ ---        ┆ ---        ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---     ┆ n         ┆ ---       │
│ str        ┆ str        ┆ f64      ┆ f64      ┆   ┆ str        ┆ str     ┆ ---       ┆ i64       │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆ i64       ┆           │
╞════════════╪════════════╪══════════╪══════════╪═══╪════════════╪═════════╪═══════════╪═══════════╡
│ Tokyo      ┆ Tokyo      ┆ 35.687   ┆ 139.7495 ┆ … ┆ Tōkyō      ┆ primary ┆ 37785000  ┆ 139268576 │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆           ┆ 4         │
│ Jakarta    ┆ Jakarta    ┆ -6.175   ┆ 106.8275 ┆ … ┆ Jakarta    ┆ primary ┆ 33756000  ┆ 136077107 │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆           ┆ 7         │
│ Delhi      ┆ Delhi      ┆ 28.61    ┆ 77.23    ┆ … ┆ Delhi      ┆ admin   ┆ 32226000  ┆ 135687260 │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆           ┆ 4         │
│ Guangzhou  ┆ Guangzhou  ┆ 23.13    ┆ 113.26   ┆ … ┆ Guangdong  ┆ admin   ┆ 26940000  ┆ 115623713 │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆           ┆ 3         │
│ Mumbai     ┆ Mumbai     ┆ 19.0761  ┆ 72.8775  ┆ … ┆ Mahārāshtr ┆ admin   ┆ 24973000  ┆ 135622662 │
│            ┆            ┆          ┆          ┆   ┆ a          ┆         ┆           ┆ 9         │
│ …          ┆ …          ┆ …        ┆ …        ┆ … ┆ …          ┆ …       ┆ …         ┆ …         │
│ Al Jabīn   ┆ Al Jabin   ┆ 14.704   ┆ 43.599   ┆ … ┆ Raymah     ┆ admin   ┆ null      ┆ 188791010 │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆           ┆ 0         │
│ Nelspruit  ┆ Nelspruit  ┆ -25.4745 ┆ 30.9703  ┆ … ┆ Mpumalanga ┆ admin   ┆ null      ┆ 171011443 │
│            ┆            ┆          ┆          ┆   ┆            ┆         ┆           ┆ 8         │
│ Gqeberha   ┆ Gqeberha   ┆ -33.9681 ┆ 25.5981  ┆ … ┆ Eastern    ┆         ┆ null      ┆ 171000008 │
│            ┆            ┆          ┆          ┆   ┆ Cape       ┆         ┆           ┆ 2         │
│ Lupane     ┆ Lupane     ┆ -18.9315 ┆ 27.807   ┆ … ┆ Matabelela ┆ admin   ┆ null      ┆ 171620660 │
│            ┆            ┆          ┆          ┆   ┆ nd North   ┆         ┆           ┆ 6         │
│ Charlotte  ┆ Charlotte  ┆ 18.342   ┆ -64.9331 ┆ … ┆ Virgin     ┆ primary ┆ null      ┆ 185003747 │
│ Amalie     ┆ Amalie     ┆          ┆          ┆   ┆ Islands    ┆         ┆           ┆ 3         │
└────────────┴────────────┴──────────┴──────────┴───┴────────────┴─────────┴───────────┴───────────┘

In [4]:
data = pl.read_csv("all_combined.csv", null_values=["null"])
data = data.with_columns(
    pl.from_epoch("timestamp", time_unit="s")
)
data

shape: (2_079_540, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ timestamp ┆ balancerI ┆ balancerI ┆ clientIpA ┆ … ┆ latencyTC ┆ latencyTL ┆ latencyFi ┆ latencyD │
│ ---       ┆ d         ┆ p         ┆ ccordingC ┆   ┆ P         ┆ S         ┆ rstByte   ┆ ownload  │
│ datetime[ ┆ ---       ┆ ---       ┆ loudflare ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ μs]       ┆ str       ┆ str       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2026-01-2 ┆ 107f211   ┆ 104.16.13 ┆ 185.32.19 ┆ … ┆ 3         ┆ 46        ┆ 15        ┆ 6        │
│ 1         ┆           ┆ 3.229     ┆ 0.187     ┆   ┆           ┆           ┆           ┆          │
│ 22:50:36  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-2 ┆ 107f156   ┆ 104.16.13 ┆ 185.32.19 ┆ … ┆ 1         ┆ 18        ┆ 37        ┆ 11       │
│ 1         ┆           ┆ 3.229     ┆ 0.187     ┆   ┆           ┆           ┆           ┆          │
│ 22:50:36  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-2 ┆ 107f211   ┆ 104.16.13 ┆ 185.32.19 ┆ … ┆ 1         ┆ 13        ┆ 5         ┆ 2        │
│ 1         ┆           ┆ 2.229     ┆ 0.187     ┆   ┆           ┆           ┆           ┆          │
│ 22:50:36  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-2 ┆ 107f179   ┆ 104.16.13 ┆ 185.32.19 ┆ … ┆ 1         ┆ 14        ┆ 10        ┆ 1        │
│ 1         ┆           ┆ 2.229     ┆ 0.187     ┆   ┆           ┆           ┆           ┆          │
│ 22:50:37  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-2 ┆ 107f174   ┆ 104.16.13 ┆ 185.32.19 ┆ … ┆ 0         ┆ 18        ┆ 7         ┆ 2        │
│ 1         ┆           ┆ 2.229     ┆ 0.187     ┆   ┆           ┆           ┆           ┆          │
│ 22:50:37  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2026-01-0 ┆ 751f10    ┆ null      ┆ 113.11.24 ┆ … ┆ 16        ┆ 47        ┆ 22        ┆ 2        │
│ 8         ┆           ┆           ┆ 0.232     ┆   ┆           ┆           ┆           ┆          │
│ 14:25:55  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-0 ┆ 751f5     ┆ null      ┆ 113.11.24 ┆ … ┆ 16        ┆ 49        ┆ 22        ┆ 2        │
│ 8         ┆           ┆           ┆ 0.232     ┆   ┆           ┆           ┆           ┆          │
│ 14:25:56  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-0 ┆ 751f8     ┆ null      ┆ 113.11.24 ┆ … ┆ 20        ┆ 51        ┆ 26        ┆ 2        │
│ 8         ┆           ┆           ┆ 0.232     ┆   ┆           ┆           ┆           ┆          │
│ 14:25:57  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-0 ┆ 751f9     ┆ null      ┆ 113.11.24 ┆ … ┆ 16        ┆ 47        ┆ 23        ┆ 1        │
│ 8         ┆           ┆           ┆ 0.232     ┆   ┆           ┆           ┆           ┆          │
│ 14:25:59  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2026-01-0 ┆ 751f6     ┆ null      ┆ 113.11.24 ┆ … ┆ 19        ┆ 51        ┆ 26        ┆ 2        │
│ 8         ┆           ┆           ┆ 0.232     ┆   ┆           ┆           ┆           ┆          │
│ 14:26:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
colocs_with_coords = colocs.join(world_cities, left_on="city", right_on="city_ascii", how="left")
colocs_with_coords = colocs_with_coords.select(["colocationCenter", "city", "country","lat", "lng", "iso3"]).unique(subset=["colocationCenter"])
colocs_with_coords

shape: (1, 6)
┌──────────────────┬────────┬─────────┬───────┬─────────┬──────┐
│ colocationCenter ┆ city   ┆ country ┆ lat   ┆ lng     ┆ iso3 │
│ ---              ┆ ---    ┆ ---     ┆ ---   ┆ ---     ┆ ---  │
│ str              ┆ str    ┆ str     ┆ f64   ┆ f64     ┆ str  │
╞══════════════════╪════════╪═════════╪═══════╪═════════╪══════╡
│ WAW              ┆ Warsaw ┆ Poland  ┆ 52.23 ┆ 21.0111 ┆ POL  │
└──────────────────┴────────┴─────────┴───────┴─────────┴──────┘

In [7]:
missing_colocs = (
    data.select(pl.col("balancerColocationCenter").unique())
    .join(colocs_with_coords, left_on="balancerColocationCenter", right_on="colocationCenter", how="full")
    .filter(pl.col("colocationCenter").is_null() | pl.col("lat").is_null())
    .unique(subset=["balancerColocationCenter"])
)
missing_colocs["balancerColocationCenter"].to_list()

[None]

Should be empty, otherwise some colocs can't be mapped to a location. May be because of name mismatch in all_colocs and worldcities

In [11]:
data_grouped_by_colocation = (
    data
    .group_by("balancerColocationCenter")
    .agg(
        pl.col("balancerId").unique().count().alias("balancerCount")
    )
)
with_coords = data_grouped_by_colocation.join(
    colocs_with_coords, 
    left_on="balancerColocationCenter", 
    right_on="colocationCenter", 
    how="left"
)
with_coords = with_coords.select(
    ["balancerColocationCenter", "city", "lat", "lng", "balancerCount", "iso3"]
)

with_coords

shape: (163, 6)
┌──────────────────────────┬─────────────┬──────────┬──────────┬───────────────┬──────┐
│ balancerColocationCenter ┆ city        ┆ lat      ┆ lng      ┆ balancerCount ┆ iso3 │
│ ---                      ┆ ---         ┆ ---      ┆ ---      ┆ ---           ┆ ---  │
│ str                      ┆ str         ┆ f64      ┆ f64      ┆ u32           ┆ str  │
╞══════════════════════════╪═════════════╪══════════╪══════════╪═══════════════╪══════╡
│ CFC                      ┆ Cacador     ┆ -26.7753 ┆ -51.015  ┆ 19            ┆ BRA  │
│ ATL                      ┆ Atlanta     ┆ 33.7628  ┆ -84.422  ┆ 1315          ┆ USA  │
│ AKL                      ┆ Auckland    ┆ -36.8492 ┆ 174.7653 ┆ 68            ┆ NZL  │
│ BNA                      ┆ Nashville   ┆ 36.1715  ┆ -86.7842 ┆ 45            ┆ USA  │
│ MAD                      ┆ Madrid      ┆ 40.4169  ┆ -3.7033  ┆ 700           ┆ ESP  │
│ …                        ┆ …           ┆ …        ┆ …        ┆ …             ┆ …    │
│ LIM                      ┆ Lima        ┆ -12.06   ┆ -77.0375 ┆ 11            ┆ PER  │
│ FSD                      ┆ Sioux Falls ┆ 43.5396  ┆ -96.7311 ┆ 7             ┆ USA  │
│ SJC                      ┆ San Jose    ┆ 37.3012  ┆ -121.848 ┆ 1064          ┆ USA  │
│ ATH                      ┆ Athens      ┆ 37.9842  ┆ 23.7281  ┆ 127           ┆ GRC  │
│ DUB                      ┆ Dublin      ┆ 53.3497  ┆ -6.2603  ┆ 404           ┆ IRL  │
└──────────────────────────┴─────────────┴──────────┴──────────┴───────────────┴──────┘

In [ ]:
with_coords.write_csv("map_data_coloc.csv")

In [17]:
by_country = (
    with_coords
    .group_by("iso3")
    .agg([
        pl.col("lat").mean().alias("mean_lat"),
        pl.col("lng").mean().alias("mean_lng"),
        pl.col("balancerCount").sum().alias("totalBalancerCount"),
    ])
)
by_country

shape: (80, 4)
┌──────┬───────────┬───────────┬────────────────────┐
│ iso3 ┆ mean_lat  ┆ mean_lng  ┆ totalBalancerCount │
│ ---  ┆ ---       ┆ ---       ┆ ---                │
│ str  ┆ f64       ┆ f64       ┆ u32                │
╞══════╪═══════════╪═══════════╪════════════════════╡
│ SWE  ┆ 58.5175   ┆ 15.0111   ┆ 421                │
│ DEU  ┆ 51.10874  ┆ 10.08778  ┆ 3148               │
│ ROU  ┆ 44.4325   ┆ 26.1039   ┆ 252                │
│ RUS  ┆ 57.232333 ┆ 53.599333 ┆ 274                │
│ ARE  ┆ 25.2631   ┆ 55.2972   ┆ 57                 │
│ …    ┆ …         ┆ …         ┆ …                  │
│ SGP  ┆ 1.3       ┆ 103.8     ┆ 2202               │
│ CHL  ┆ -33.4372  ┆ -70.6506  ┆ 208                │
│ QAT  ┆ 25.2867   ┆ 51.5333   ┆ 28                 │
│ PRT  ┆ 38.7122   ┆ -9.134    ┆ 142                │
│ LBN  ┆ 33.8981   ┆ 35.5058   ┆ 7                  │
└──────┴───────────┴───────────┴────────────────────┘

In [18]:
by_country.write_csv("map_data_country.csv")